version: '3'
services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ricky
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: simple_nest
    ports:
      - 3320:3306
  redis:
    image: redis:latest
    ports:
      - 6381:6379
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    ports:
      - 5677:5672
      - 15677:15672
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: adminpassword
  k6:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test/k6-config.js:/config.js
    command: run /config.js
